### ISSUE TITLE
Recommendation System Scenario

### ISSUE THREAD

**Issue by StephenAnokye94** [oisintheginger/mscfinalproject#101]
Kindly review below for me

Jenni is a college student who is using Housing Made Easy to find a suitable place to live in Baltimore. She has been browsing the app and has already selected and viewed multiple houses that piqued her interest. To provide Jenni with personal recommendations for rental properties that align with her preferences.
We use the features from those houses Jenni likes as input to our algorithm so it recommends similar houses to what Jenni likes by providing a list of other houses with those features.
With the recommendation system in place, Jenni receives personalized recommendations that match her preferences. As she continues to use the application, the system adapts to her changing needs (if/when she likes some more properties) that updates , providing her with increasingly relevant rental listings.

**Comment by CharlotteMartin1998** [comment]
Stop saying OUR/ WE -> Scientific writing please!!!!!
This is better:

Jenni is a college student who is using Housing Made Easy to find a suitable place to live in Baltimore. She has already selected and viewed multiple properties that piqued her interest. To provide Jenni with personal recommendations for rental properties that align with her preferences by using the features from Jenni's preferred properties. These properties are input to the algorithm thereby recommending similar properties. The properties with similar feature are provided to Jenni in a list.
With the recommendation system in place, Jenni receives personalized recommendations that match her preferences. As she continues to use the application, the system adapts to her needs (if/when she likes some more properties), providing her with increasingly relevant rental listings.

**Comment by StephenAnokye94** [comment]
Thanks 
How is the final edit below

Jenni is a college student who is using Housing Made Easy to find a suitable place to live in Baltimore. She has already selected and viewed multiple properties that piqued her interest. To provide Jenni with personal recommendations for rental properties that align with her preferences by using the features from Jenni's preferred properties. The features of the preferred properties are input to the algorithm thereby recommending similar properties. The properties with similar features are provided to Jenni in a list.

**Comment by CharlotteMartin1998** [comment]
Try this, there's still some redundancy:



> Thanks How is the final edit below
> 
> Jenni is a college student who is using Housing Made Easy to find a suitable place to live in Baltimore. She has already selected and viewed multiple properties that piqued her interest. To provide Jenni with personal recommendations, the features of the preferred properties are input to the algorithm. The output, which Jenni will view as an additional property list, will be the recommended similar properties.

**Comment by StephenAnokye94** [comment]
I agree with this. Thank you.
